### ISSUE TITLE
Allow the user to add more sections to the changelog instead of just features and fixes

### ISSUE THREAD

**Issue by silkentrance** [ericmatthys/grunt-changelog#24]
I am currently working on a patch that will allow the user to add custom sections to the changelog, e.g.

   Release v0.2.1 (2014-11-10)

   API Changes:

```
 - Tool#extend now expects three parameters instead of just one
```

   API Deprecations:

```
 - Tool#shutdown is now deprecated, use Tool#quit instead
```

   New Features:

```
 - ...
```

   Bug Fixes:

```
 - ...
```

   Miscellaneous:

```
 - implemented more test cases
 - integrated Travis CI
 - ...
```

and so on.

I will pour you in a pull request as soon as it is done. Of course I will try to make it backwards compatible so that existing build configurations need not be changed.

**Comment by silkentrance** [comment]
@ericmatthys *ping* - are you still supporting this?

**Comment by mischah** [comment]
Looks interesting. Guess you are not the only one, who might be interested in that. 
Will your changes introduce breaking changes? Or is it backward compatible with existing configs?

**Comment by silkentrance** [comment]
I am sure that it is backwards compatible, see the configureSections() function which defaults to the original behaviour and will mix in the new options.sections only when available.

**Comment by silkentrance** [comment]
I will rebase this to a single commit ASAP.

**Comment by mischah** [comment]
:+1:

Don’t forget to add test :blush:

**Comment by silkentrance** [comment]
Will do.

**Comment by silkentrance** [comment]
Closing since I no longer have need for this.
