### ISSUE TITLE
Use format=%B instead of format=%s as %s collapses newlines

### ISSUE THREAD

**Issue by silkentrance** [ericmatthys/grunt-changelog#25]
Having a commit message like so

 - added X
 - removed Y

using git --pretty=format:%s will collapse existing lines into a single line like so

 - added X - removed Y

Using %B instead will preserve the original layout of the commit message.

**Comment by ericmatthys** [comment]
This should probably be configurable. `%s` just includes the subject, while `%B` includes both the subject and body. I think many users do not want the entire body of their commit message in the changelog when the subject is enough.

**Comment by ericmatthys** [comment]
https://github.com/ericmatthys/grunt-changelog/pull/16

**Comment by silkentrance** [comment]
Okay, will make a new request that will introduce a config option for controlling this behaviour.

**Comment by mischah** [comment]
No need for that. We are much more flexible with the new option `logArguments`.

See:
- #30
- https://github.com/ericmatthys/grunt-changelog/tree/develop#optionslogarguments
- https://github.com/ericmatthys/grunt-changelog/tree/develop#custom-git-log-arguments
