### ISSUE TITLE
Existing default regexes produce random matches

### ISSUE THREAD

**Issue by silkentrance** [ericmatthys/grunt-changelog#33]
While working on #24, I found that while all existing test cases do actually work, the underlying regular expressions, especially the default ones, generate rather random results. See below.

Considering the following output of regular expressions and their respective matches

```
regex: "/^(.*)fixes #\d+:?(.*)$/i":"Fix 1 2 3."
regex: "/^(.*)fixes #\d+:?(.*)$/i":"Fix 4 5 6."
regex: "/^(.*)fixes #\d+:?(.*)$/i":"Fix 7 8 9."
regex: "/^(.*)closes #\d+:?(.*)$/i":"Feature 1 2 3."
regex: "/^(.*)closes #\d+:?(.*)$/i":"Feature 4 5 6."
regex: "/^(.*)closes #\d+:?(.*)$/i":"Feature 7 8 9."
```

it would seem that the matches produced by the default regular expressions are lucky at best.

Perhaps reworking these regular expressions would be a wise move?

**Comment by mischah** [comment]
I don’t get it :expressionless:

This is the default `featureRegex`defined [over here](https://github.com/ericmatthys/grunt-changelog/blob/develop/tasks/changelog.js#L19):
http://refiddle.com/1v55

And this is the default `fixRegex` defined [over here](https://github.com/ericmatthys/grunt-changelog/blob/develop/tasks/changelog.js#L20):
http://refiddle.com/1v56

I guess they both could be simplified but they seem to work solid for me.

**Comment by silkentrance** [comment]
Well, I guess it must have been very late. In fact, the matches should have included the closes and fixes parts as well, somehow they got cut off. That is why I wondered.
Closing as invalid.
