### ISSUE TITLE
Would it be useful to add an option for passing in custom data to the template?

### ISSUE THREAD

**Issue by silkentrance** [ericmatthys/grunt-changelog#40]
I was wondering whether allowing the user to pass in additional data to the template would be of any value, e.g.

```
options: {
   data: {
      package: packageObject,
      ...
   }
}
```

Since that data could be collected dynamically from e.g. the package.json file, for example a list of contributors, the author and so on, it would allow the user to customize the change log even more.

What do you think?

**Comment by mischah** [comment]
Interesting idea even it’s not needed in my use case.
Would love to get some feedback by others before deciding whether to implement this.

**Comment by ericmatthys** [comment]
I could see this being useful.

**Comment by silkentrance** [comment]
Great, I would like to extend upon this by allowing the user to pass in a function as the data and also for individual entries in that data, e.g.

```
data : function () {
     return {
         foo : function () {
             return { 'composite' : 1, 'result' : 2 };
         },
         bar : 'foo'
     };
}
```

so that the data can be late bound or dynamically updated during it being injected into the template(s).

**Comment by silkentrance** [comment]
Closing since I no longer have need for this.
